module AnsiEscapeCodes

// Colors
let BACK_BLACK = "\x1B[40m"
let BACK_RED = "\x1B[41m"
let BACK_GREEN = "\x1B[42m"
let BACK_YELLOW = "\x1B[43m"
let BACK_BLUE = "\x1B[44m"
let BACK_PURPLE = "\x1B[45m"
let BACK_CYAN = "\x1B[46m"
let BACK_WHITE = "\x1B[107m"
let BACK_ORANGE = "\x1B[48;5;208m"

let FORE_BLACK = "\x1B[30m"
let FORE_RED = "\x1B[31m"
let FORE_GREEN = "\x1B[32m"
let FORE_YELLOW = "\x1B[33m"
let FORE_BLUE = "\x1B[34m"
let FORE_PURPLE = "\x1B[35m"
let FORE_CYAN = "\x1B[36m"
let FORE_WHITE = "\x1B[97m"
let FORE_ORANGE = "\x1B[38;5;208m"

// Styles
let RESET = "\x1B[0m"
let BOLD = "\x1B[1m"
let DIM = "\x1B[2m"
let UNDERLINE = "\x1B[4m"
let BLINK = "\x1B[5m"
let REVERSE = "\x1B[7m"
let HIDDEN = "\x1B[8m"
let STRIKETHROUGH = "\x1B[9m"
let MAGICAL = "\x1B[6m"
let SLOW_BLINK = "\x1B[25m"
let FAST_BLINK = "\x1B[6m"
let ITALIC = "\x1B[3m"
let OVERLINE = "\x1B[53m"
let DOUBLE_UNDERLINE = "\x1B[21m"
let FRAMED = "\x1B[51m"
let ENCIRCLED = "\x1B[52m"
let OVERLINED = "\x1B[55m"
let BOLD_FAINT = "\x1B[20m"
let POSITIVE_IMG = "\x1B[27m"

// Cursor
let UP = "\x1B[A"
let DOWN = "\x1B[B"
let FORWARD = "\x1B[C"
let BACKWARD = "\x1B[D"
let POS = "\x1B[H"
let CLEAR = "\x1B[2J"
let CLEAR_FORWARD = "\x1B[0J"
let CLEAR_BACKWARD = "\x1B[1J"
let CLEAR_LINE = "\x1B[2K"
let CLEAR_LINE_FORWARD = "\x1B[0K"
let CLEAR_LINE_BACKWARD = "\x1B[1K"
let SAVE_POS = "\x1B[s"
let RESTORE_POS = "\x1B[u"
let NEXT_LINE = "\x1B[E"
let PREV_LINE = "\x1B[F"
